// <auto-generated />
//
// Este archivo describe el modelo tal como queda despues de aplicar la migracion. Lo usan las
// herramientas de Entity Framework Core para calcular la diferencia con el modelo actual y
// generar la siguiente migracion. No debe editarse a mano salvo para acompanar un cambio real
// del modelo.
using System;
using Licitaciones.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Licitaciones.Infrastructure.Migraciones;

[DbContext(typeof(LicitacionesDbContext))]
[Migration("20260818120000_InicialEsquemaLicitaciones")]
partial class InicialEsquemaLicitaciones
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Licitaciones.Domain.Entidades.Licitacion", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Codigo")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("codigo");

                b.Property<string>("CodigoNormalizado")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("codigo_normalizado");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("deleted_at");

                b.Property<int>("Estado")
                    .HasColumnType("integer")
                    .HasColumnName("estado");

                b.Property<DateTimeOffset>("FechaCierre")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("fecha_cierre");

                b.Property<decimal>("PresupuestoEstimadoCrc")
                    .HasColumnType("numeric(18,2)")
                    .HasColumnName("presupuesto_estimado_crc");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("character varying(300)")
                    .HasColumnName("titulo");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.HasKey("Id")
                    .HasName("pk_licitaciones");

                b.HasIndex("CodigoNormalizado")
                    .IsUnique()
                    .HasDatabaseName("ux_licitaciones_codigo_normalizado");

                b.HasIndex("Estado")
                    .HasDatabaseName("ix_licitaciones_estado");

                b.HasIndex("FechaCierre")
                    .HasDatabaseName("ix_licitaciones_fecha_cierre");

                b.ToTable("licitaciones", null, t =>
                    {
                        t.HasCheckConstraint("ck_licitaciones_presupuesto_positivo", "presupuesto_estimado_crc > 0");

                        t.HasCheckConstraint("ck_licitaciones_estado_valido", "estado IN (0, 1, 2)");
                    });
            });

        modelBuilder.Entity("Licitaciones.Domain.Entidades.NivelAprobacion", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Aprobador")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("aprobador");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<decimal?>("MontoMaximoCrc")
                    .HasColumnType("numeric(18,2)")
                    .HasColumnName("monto_maximo_crc");

                b.Property<decimal>("MontoMinimoCrc")
                    .HasColumnType("numeric(18,2)")
                    .HasColumnName("monto_minimo_crc");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.HasKey("Id")
                    .HasName("pk_niveles_aprobacion");

                b.HasIndex("MontoMinimoCrc")
                    .IsUnique()
                    .HasDatabaseName("ux_niveles_aprobacion_monto_minimo");

                b.ToTable("niveles_aprobacion", null, t =>
                    {
                        t.HasCheckConstraint("ck_niveles_aprobacion_minimo_positivo", "monto_minimo_crc > 0");

                        t.HasCheckConstraint("ck_niveles_aprobacion_maximo_positivo", "monto_maximo_crc IS NULL OR monto_maximo_crc > 0");

                        t.HasCheckConstraint("ck_niveles_aprobacion_rango_coherente", "monto_maximo_crc IS NULL OR monto_maximo_crc >= monto_minimo_crc");
                    });
            });

        modelBuilder.Entity("Licitaciones.Domain.Entidades.Oferta", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("FechaRegistro")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("fecha_registro");

                b.Property<Guid>("LicitacionId")
                    .HasColumnType("uuid")
                    .HasColumnName("licitacion_id");

                b.Property<decimal>("MontoOfertadoCrc")
                    .HasColumnType("numeric(18,2)")
                    .HasColumnName("monto_ofertado_crc");

                b.Property<Guid>("ProveedorId")
                    .HasColumnType("uuid")
                    .HasColumnName("proveedor_id");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.HasKey("Id")
                    .HasName("pk_ofertas");

                b.HasIndex("ProveedorId")
                    .HasDatabaseName("ix_ofertas_proveedor");

                b.HasIndex("LicitacionId", "MontoOfertadoCrc")
                    .HasDatabaseName("ix_ofertas_licitacion_monto");

                b.HasIndex("LicitacionId", "ProveedorId")
                    .IsUnique()
                    .HasDatabaseName("ux_ofertas_licitacion_proveedor");

                b.ToTable("ofertas", null, t =>
                    {
                        t.HasCheckConstraint("ck_ofertas_monto_positivo", "monto_ofertado_crc > 0");
                    });
            });

        modelBuilder.Entity("Licitaciones.Domain.Entidades.Proveedor", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<DateTimeOffset?>("DeletedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("deleted_at");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("nombre");

                b.Property<string>("NombreNormalizado")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("nombre_normalizado");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.HasKey("Id")
                    .HasName("pk_proveedores");

                b.HasIndex("NombreNormalizado")
                    .IsUnique()
                    .HasDatabaseName("ux_proveedores_nombre_normalizado");

                b.ToTable("proveedores", (string)null);
            });

        modelBuilder.Entity("Licitaciones.Domain.Entidades.TipoCambio", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<bool>("Activo")
                    .HasColumnType("boolean")
                    .HasColumnName("activo");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<decimal>("CrcPorUsd")
                    .HasColumnType("numeric(18,2)")
                    .HasColumnName("crc_por_usd");

                b.Property<DateTimeOffset>("FechaVigencia")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("fecha_vigencia");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<uint>("Version")
                    .IsConcurrencyToken()
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("xid")
                    .HasColumnName("xmin");

                b.HasKey("Id")
                    .HasName("pk_tipos_cambio");

                b.HasIndex("Activo")
                    .IsUnique()
                    .HasDatabaseName("ux_tipos_cambio_unico_activo")
                    .HasFilter("activo");

                b.HasIndex("FechaVigencia")
                    .HasDatabaseName("ix_tipos_cambio_fecha_vigencia");

                b.ToTable("tipos_cambio", null, t =>
                    {
                        t.HasCheckConstraint("ck_tipos_cambio_valor_positivo", "crc_por_usd > 0");
                    });
            });

        modelBuilder.Entity("Licitaciones.Domain.Entidades.Oferta", b =>
            {
                b.HasOne("Licitaciones.Domain.Entidades.Licitacion", "Licitacion")
                    .WithMany("Ofertas")
                    .HasForeignKey("LicitacionId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_ofertas_licitaciones_licitacion_id");

                b.HasOne("Licitaciones.Domain.Entidades.Proveedor", "Proveedor")
                    .WithMany("Ofertas")
                    .HasForeignKey("ProveedorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_ofertas_proveedores_proveedor_id");

                b.Navigation("Licitacion");

                b.Navigation("Proveedor");
            });

        modelBuilder.Entity("Licitaciones.Domain.Entidades.Licitacion", b =>
            {
                b.Navigation("Ofertas");
            });

        modelBuilder.Entity("Licitaciones.Domain.Entidades.Proveedor", b =>
            {
                b.Navigation("Ofertas");
            });
#pragma warning restore 612, 618
    }
}
